---
- name: Clone a github repository {{ ec2_tf_source|basename }}
  git:
    repo: '{{ ec2_tf_source }}'
    dest: '{{ ec2_tf_module_download_path }}'
    clone: yes
    update: yes
    version: main

 