---
- name: create random string
  ansible.builtin.debug:
  set_fact:
    random_id: "{{ lookup('community.general.random_string', length=12, min_special=0, special=false, lower=false, upper=false) }}"
- debug:
    var: random_id

- name: tls private key
  community.crypto.openssl_privatekey:
  variables:
    type: '{{ private_key_type }}'
    size: '{{ private_key_size }}'
    path: '{{ TLS_privatekey_file_path }}'
    force: true
    return_content: true
    state: present
  register: openssh_key

- set_fact:
    private_openssh_key: "{{ openssh_key['privatekey'] }}"

- name: Generate an OpenSSL public key from private key
  community.crypto.openssl_publickey:
    force: true
    format: "OpenSSH"
    path: '{{ TLS_publickey_file_path }}'
    privatekey_content: "{{ private_openssh_key }}"
    return_content: true
  register: openssh_public_key                   

- set_fact:
    openssh_public_key: "{{ openssh_public_key['publickey'] }}"

- name: Print openssh_public_key variable
  ansible.builtin.debug:
    msg: "openssh_public_key: '{{ openssh_public_key }}'"

- name: Create an AWS key pair
  amazon.aws.ec2_key:
    name: TF_key-{{ random_id }}                 
    key_material: "{{ openssh_public_key }}"    
    state: present
  register: keypair_output

- debug:
    var: keypair_output

- name: Creating a file with content             
  copy:
    dest: '{{ file_name }}'
    mode: '0777'
    content: |
      '{{ private_openssh_key }}'




         














