---
- name: Gather information about ec2 AMIs
  amazon.aws.ec2_ami_info:
    owners: '{{ aws_ami_owner }}'
    filters:
      name: "{{aws_ami_value}}"
      virtualization-type: "{{virtualization_value}}"
  register: ami_info_output

- set_fact:
    ami_id: '{{ ami_info_output["images"][0]["image_id"] }}'

- name: Create random string
  set_fact:
    random_id: "{{ lookup('community.general.random_string', length=5, min_special=0, special=false) }}"

- debug:
    var: random_id

- name: Create a directory for storing public and private key files
  ansible.builtin.file:
    path: "{{directory_keyfiles}}"
    state: directory
    mode: '0777'

- name: Generate OpenSSL private keys
  community.crypto.openssl_privatekey:
    type: '{{ private_key_type }}'
    size: '{{ private_key_size }}'
    path: '{{ tls_privatekey_file_path }}'
    force: true
    return_content: true
    state: present
  register: openssh_key

- set_fact:
    private_openssh_key: "{{ openssh_key['privatekey'] }}"

- name: Generate an OpenSSL public key from private key
  community.crypto.openssl_publickey:
    force: true
    format: "OpenSSH"
    path: '{{ tls_publickey_file_path }}'
    privatekey_content: "{{ private_openssh_key }}"
    return_content: true
  register: openssh_public_key                   #publickey

- set_fact:
    openssh_public_key: "{{ openssh_public_key['publickey'] }}"

- name: Print openssh_public_key variable
  ansible.builtin.debug:
    msg: "openssh_public_key: '{{ openssh_public_key }}'"

- name: Create an AWS key pair
  amazon.aws.ec2_key:
    name: TF_key-{{ random_id }}                 #compare random_id variable with terraform script
    key_material: "{{ openssh_public_key }}"     #compare public_key_openssh variable with terraform script
    state: present
  register: keypair_output

- debug:
    var: keypair_output

- name: Creating a file with content             #confirm destination filename from terraform script
  copy:
    dest: '{{ file_name }}'
    mode: '0777'
    content: |
      '{{ private_openssh_key }}'