- name: Read terraform output
  command: chdir='{{ vm_tf_module_download_path }}' terraform output -json
  register: gen_ai_demo_tf_output

- debug:
    var: gen_ai_demo_tf_output

- set_fact:
    gen_ai_demo_tf_output: "{{ gen_ai_demo_tf_output.stdout }}"

- debug:
    var: gen_ai_demo_tf_output

- block:
    - name: "Checking Terraform resource"
      debug:
        msg: "Terraform cannot delete the resource because it is not found in the state file. Manual intervention is required."
    - meta: end_play
  when: gen_ai_demo_state == 'absent' and gen_ai_demo_tf_output | length == 0

- set_fact:
    instance_id: "{{ gen_ai_demo_tf_output.id.value }}"
    tags: "{{ gen_ai_demo_tf_output.tags_all.value }}"
  when: gen_ai_demo_tf_output | length > 0

- set_fact:
    random_id: "{{ tags.Name.split('-')[-1] }}"
  when: tags | length > 0

- amazon.aws.ec2_instance_info:
    instance_ids: "{{ instance_id }}"
  register: ec2_info
  when: instance_id | length > 0

- debug:
    var: ec2_info

- set_fact:
    ec2_instance: "{{ ec2_info.instances[0] }}"
  when: ec2_info.instances is defined

- set_fact:
    keypair_name: "{{ ec2_instance['key_name'] }}"
    ami_id: "{{ ec2_instance['image_id'] }}"
    ec2_update: true
  when: ec2_instance | length > 0

- ansible.builtin.debug:
    msg:
    - "instance_id: {{ instance_id }}"
    - "random_id: {{ random_id }}"
    - "keypair_name: {{ keypair_name }}"
