---
- name: playbook using amazon linux ec2
  hosts: localhost
  tasks:
    - name: running a role amazon linux ec2 non default vpc
      ansible.builtin.import_role:
        name: amazon_linux_ec2_non_default_vpc
      vars:
        ec2_state: present
       
